# f = open("1.txt", "r")
# p = f.read()
# print("read")
# print(p)
# f.seek(0, 0)
# p = f.read(2)
# print("read(2)")
# print(p)
# f.seek(0, 0)
# p = f.readline()
# print("readline")
# print(p)
# f.seek(0, 0)
# p = f.readlines()
# print("readlines")
# print(p)
# f.close()

f = open("1.txt","w+")
f.write("hello")
f.flush()
f.seek(0,0)
print(f.read())
f.close()
